spring.application.name=transport

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#kinaplozza milyen sql-eket futtat: 
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never

spring.jpa.open-in-view=false

#delay funkcio beallitasa (nem lepcsozetes funkciohoz hasznaltam):
transport.delay.revenueReductionPercent=10

#Lepcsozetes delay letrehozasa:
transport.delay.revenueReductionPercent30=10
transport.delay.revenueReductionPercent60=20
transport.delay.revenueReductionPercent120=30

#JWT beallitasok:
transport.jwt.secret=valamienyem322
transport.jwt.issuer=transport
transport.jwt.durationSeconds=600